const globe = document.querySelector("#turtle");
const button = document.querySelector("#shake");
const message = document.querySelector("#message");
 
const messages = [
  "A cloud weighs around a million tonnes.",
  "Identical twins don’t have the same fingerprints.",
  "Earth’s rotation is changing speed.",
  "Leftover pasta has extra health benefits.",
  "Parents in the US consistently rank as the world's unhappiest. ",
  "A thunderstorm called Hector the Convector arrives everyday at 3pm.",
  "Earlobes have no biological purpose.",
  "When you're reading – even silently – the muscles of your mouth, tongue and larynx activate.",
  "Mars isn’t actually round. ",
  "There’s no such thing as zero-calorie foods.",
  "Around 8–10 per cent of people grind their teeth at night.",
  "The Universe's average colour is called 'Cosmic latte'.",
  "Water might not be wet.",
  "All the world’s bacteria stacked on top of each other would stretch for 10 billion light-years.",
  "The fear of long words is called Hippopotomonstrosesquippedaliophobia.",
  "The world’s oldest dog lived to 29.5 years old. ",
  "The world’s oldest cat lived to 38 years and three days old.",
  "We've only explored 0.001 per cent of the ocean floor.",
  "Mount Everest isn't the tallest mountain on Earth.",
  "Our solar system has a wall.",
  "Most maps of the world are wrong.",
  "The Moon is gradually drifting away from Earth.",
  "Earth’s poles are moving.",
  "Cats prefer to sleep on their left.",
  "You don’t actually lose most of your heat through your head.",
  "The T.rex likely had feathers.",
  "Football teams wearing red kits play better.",
  "Board games can reduce your risk of dementia.",
  "Sound can be minus decibels.",
  "A horse normally has more than one horsepower.",
  "Finland is the happiest country on Earth.",
  "You can yo-yo in space.",
  "Polar bears aren’t actually white.",
  "You travel 2.5 million km a day around the Sun without realising. ",
  "The Bermuda Triangle is no more hazardous than any other busy ocean route.",
  "There’s a planet mostly made from diamond.",
  "It’s surprisingly easy to escape quicksand.",
  "A penguin can reach depths of 550m in one dive.",
  "Animals can be allergic to humans.",
  "LEGO bricks withstand compression better than concrete.",
  "It's almost impossible to get too much sugar from fresh fruit.",
  "You don't like the sound of your own voice because of the bones in your head.",
  "A rainbow on Venus is called a glory.",
  "Protons look like peanuts, rugby balls, bagels, and spheres.",
  "You remember more dreams when you sleep badly.",
  "The Moon is shrinking.",
  "You can smell ants",
  "People who eat whatever they want and stay slim have a slow metabolism, not fast.",
  "You’re taller in the morning than at night",
  "The oldest goldfish lived to be 43 years old",
  "It rains red in some parts of the world",
  "Honey never expires",
  "First-time tourists to Paris can be so disappointed, they get sick",
  "Pilots and co-pilots consume different in-flight meals",
  "In Sweden, Cool Ranch Doritos are called “Cool American”",
  "A flamingo’s pink color comes from its food",
  "The oldest piece of cake is nearly 4,000 years old",
  "New Zealand has more sheep than people",
  "Avocados are a fruit, not a vegetable.",
  "The Eiffel Tower can be 15 cm taller during the summer.",
  "Australia is wider than the moon. ",
  "The Ancient Romans used to drop a piece of toast into their wine for good health. Hence why we 'raise a toast.'",
  "The unicorn is the national animal of Scotland.",
  "The first airplane flew on December 17, 1903.",
  "Venus is the only planet to spin clockwise.",
  "Competitive art used to be an Olympic sport.",
  "There’s only one letter that doesn’t appear in any American state name. (Q)",
  "Louboutin's iconic red soles were inspired by Andy Warhol.",
  "Big Ben's clock stopped at 10:07 p.m. on 27 May 2005",
  "Queen Elizabeth II was a trained mechanic.",
  "The last letter added to the English alphabet was 'J'",
  "Bees can recognize and differentiate human faces.",
  "The moon has moonquakes.",
  "A jiffy is an actual unit of time. It's 1/100th of a second.",
  "Bananas are technically berries.",
  "Japan has over 200 flavors of Kit Kats.",
  "The Eiffel Tower was originally intended for Barcelona.",
  "Dolphins have names for one another.",
  "The letter 'E' is the most popular letter in the alphabet.",
  "KFC is the meal of choice on Christmas Day in Japan.",
  "Mariah Carey holds the record for the most number-one singles by a solo artist on the Billboard Hot 100 chart.",
  "You share your birthday with around 19 million people. ",
  "Beyoncé is the most awarded artist at the Grammys.",
  "Lemons float, but limes sink. ",
  "Japan has one vending machine for every 40 people.",
  "The shortest war in history, the Anglo-Zanzibar War, lasted 38 minutes.",
  "The Atlantic Ocean is saltier than the Pacific Ocean.",
  "One season on Saturn lasts about seven Earth years.",
  "The name LEGO comes from the Danish words “Leg Godt,” which means 'play well.'",
  "Snow White was the first Disney Princess to have a full-length movie. It was created way back in 1938.",
  "Potatoes were the first food to be grown in space.",
  "Donald Duck has appeared in the most Disney movies from 1934 to 1999 - all 197 of them! Which is more than Mickey Mouse, who has appeared in 167.",
  "Plants came before seeds.",
  "Your cat sits on your laptop because it smells of you, not because it’s warm.",
  "People are walking faster than they used to",
  "The deepest part of the ocean reaches more than 10,900m.",
  
];
 
button.addEventListener("click", () => {
  globe.classList.add("shaking");
  setTimeout(() => globe.classList.remove("shaking"), 600);
 
  const pick = Math.floor(Math.random() * messages.length);
  message.textContent = messages[pick];
});